version: '3.8'
services:
  db:
    build:
      context: contextPath
      dockerfile: DockerFile-Mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_produits
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql 
  web:
    build:
      context: . 
      dockerfile: DockerFile 
    depends_on:
      - db
    ports:
      - "80:80" 
    volumes:
      - ./www:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gestion_produits

volumes:
  db_data:
