FROM mysql:8.3

COPY ./database/gestion_produits.sql /docker-entrypoint-initdb.d/
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=gestion_produits
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password


