FROM mysql:5.7

COPY ./database/gestion_produits.sql /docker-entrypoint-initdb.d/
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=gestion_produits
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=password


