# Cette application est compatible avec php 5
FROM php:5.6-apache

# Copier le dossier www dans le conteneur
COPY www/ /var/www/html/

RUN chmod 777 /var/www/html/uploads

RUN docker-php-ext-install mysqli